import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/Banner"
import Card from "../components/card/Card"

import coffeeStoresData from "../data/coffee-stores.json"

export default function Home(props) {

  const handleOnBannerBtnClick = () => {
    console.log("Banner btn");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={"View store nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} alt={""} priority />
        </div>
        {props.coffeeStores.length > 0 && (<>
          <h2 className={styles.heading2}>Toronto Stores</h2>
          <div className={styles.cardLayout}>
            {props.coffeeStores.map((coffeeStore) => (<Card
              key={coffeeStore.id}
              name={coffeeStore.name}
              imgUrl={coffeeStore.imgUrl}
              href={`coffee-store/${coffeeStore.id}`}
              className="card"
            />
            ))}
          </div>
        </>)}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  //normally fetched here, then passed to the component by returning props
  const options = {
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: 'fsq3T09iEGFvhqBvIrBi3JOZ/elz+lAZQ325tloliSbXhDA='
    }
  };
  
  const data = fetch('https://api.foursquare.com/v3/places/search?query=coffee&ll=39.28760039194706%2C-76.63560688853784&limit=6', options)
    .then(response => response.json())
    .then(response => console.log(response))
    .catch(err => console.error(err));

  return {
    props: {
      coffeeStores: coffeeStoresData,
    }, //will be passed to the page component as props
  }
}
